repos:
-   repo: local
    hooks:
#    -   id: flake8
#        name: flake8
#        entry: flake8
#        args: ["--config=setup.cfg"]
#        language: python
#        types: [python]
#        always_run: true
    -   id: pytest
        name: pytest
        entry: pytest --cov
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
