[tool.poetry]
name = "auth-fapi"
version = "0.1.0"
description = "Auth service for educational purposes"
authors = ["Ilia Dmitriev <ilia.dmitriev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
aioredis = "^2.0.1"
aiosqlite = "^0.17.0"
asyncmy = "^0.2.5"
asyncpg = "^0.27.0"
fastapi = "^0.88.0"
SQLAlchemy = "^1.4.45"
uvicorn = "^0.20.0"
alembic = "^1.9.0"
greenlet = "^2.0.1"
pydantic = {extras = ["email"], version = "^1.10.4"}
passlib = "^1.7.4"
python-jose = "^3.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pytest-asyncio = "^0.20.3"
pytest-cov = "^4.0.0"
asgi-lifespan = "^2.0.0"
httpx = "^0.23.1"
flake8 = "^5.0.4"
flake8-isort = "^6.0.0"
flake8-quotes = "^3.3.2"
flake8-docstrings = "^1.6.0"
flake8-annotations = "^2.9.1"
flake8-comprehensions = "^3.10.1"
black = "^22.12.0"
flake8-polyfill = "^1.0.2"
pep8-naming = "^0.13.2"
pdoc3 = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "-rx -rP -v"