from os import environ as env

DATABASE_DRIVER = env.get('DATABASE_DRIVER')
DATABASE_NAME = env.get('DATABASE_NAME')
DATABASE_USER = env.get('DATABASE_USER')
DATABASE_PASSWORD = env.get('DATABASE_PASSWORD')
DATABASE_HOST = env.get('DATABASE_HOST')
DATABASE_PORT = env.get('DATABASE_PORT')

DATABASE_URL = f'{DATABASE_DRIVER}://{DATABASE_USER}:{DATABASE_PASSWORD}' \
               f'@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'
