name: CI unittests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unittests:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '#notest')"

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Pytest with Coverage
        run: |
          uv run pytest -v --cov=. --cov-report=term-missing --cov-report=html --cov-branch

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.python-version }}
          path: htmlcov
          retention-days: 3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check if coverage under 100
        run: |
          coverage report --fail-under=100
